<a href="https://colab.research.google.com/github/aqilaazza/mini-bootcamp-data-analyst-python/blob/main/01-basic-python/numpy-universal-random-module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fungsi Universal di dalam Library NumPy

Fungsi ini mencangkup operasi aritmatika, trigonometri, eksponensial dan banyak lagi

In [ ]:
import numpy as np

In [ ]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

aritmatika

In [ ]:
# penambahan
np.add(arr_a, arr_b)

array([5, 7, 9])

In [ ]:
# perkalian
np.multiply(arr_a, arr_b)

array([ 4, 10, 18])

fungsi statistik

In [ ]:
arr_c = np.array([1, 2, 3, 4, 5, 5])

In [ ]:
np.mean(arr_c)

np.float64(3.3333333333333335)

In [ ]:
np.median(arr_c)

np.float64(3.5)

In [ ]:
np.std(arr_c)

np.float64(1.4907119849998598)

In [ ]:
np.log(arr_c)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.60943791])

In [ ]:
np.exp(arr_c)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 148.4131591 ])

Fungsi Trigonometri

In [ ]:
np.sin(arr_c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.95892427])

In [ ]:
np.cos(arr_c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.28366219])

In [ ]:
np.tan(arr_c)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -3.38051501])

# Latihan Fungsi Universal NumPy

In [ ]:
import numpy as np

In [ ]:
# Perhatikan array berikut:
arr_a = np.array([2,3,2,1,5])
arr_b = np.array([2,5,5,7,9])

1. Dengan menggunakan fungsi universal, tampilkan hasil perkalian antara arr_a dan arr_b?

In [ ]:
np.multiply(arr_a, arr_b)

array([ 4, 15, 10,  7, 45])

2. Berapakan selisih rata-rata antara arr_a dan arr_b?

In [ ]:
np.subtract(np.mean(arr_a), np.mean(arr_b))

np.float64(-2.9999999999999996)

3. Berapakah selisih jumlah antara arr_a dan arr_b?

In [ ]:
np.subtract(np.sum(arr_a), np.sum(arr_b))

np.int64(-15)

In [ ]:
nilai = [[70,45,56,66],[86,50,60,90],[90,75,84,93],[30,55,89,65]]
arr_nilai = np.array(nilai)
arr_nilai

array([[70, 45, 56, 66],
       [86, 50, 60, 90],
       [90, 75, 84, 93],
       [30, 55, 89, 65]])

4. Berapa nilai eksponential dari arr_nilai di baris ke 4 dan kolom ke 2?

In [ ]:
np.exp(arr_nilai[3,1])

np.float64(7.694785265142018e+23)

5. Berapa nilai selisih sinus dari total baris pertama dan cosinus dari total kolom pertama arr_nilai?

In [ ]:
arr_nilai

array([[70, 45, 56, 66],
       [86, 50, 60, 90],
       [90, 75, 84, 93],
       [30, 55, 89, 65]])

In [ ]:
x = np.sum(arr_nilai[0])
x

np.int64(237)

In [ ]:
y = np.sum(arr_nilai[:, 0])
y

np.int64(276)

In [ ]:
np.subtract(np.sin(x), np.cos(y))

np.float64(-1.8779422036551292)

# Module Random

NumPy menyediaakan module numpy random untuk menghasilkan angka acak. Sangat berguna seperti simulasi, statistik, machine learning dan lainnya

In [ ]:
import numpy as np

Membuat angka random

In [ ]:
np.random.rand(3) #membuat 1 dimensi yang berisi 3 elemen

array([0.56786108, 0.13119865, 0.30034506])

In [ ]:
np.random.rand(3, 2) #membuat 2 dimensi yang berisi 3 baris 2 kolom

array([[0.19806424, 0.6550249 ],
       [0.32350281, 0.9416879 ],
       [0.53537159, 0.27509275]])

In [ ]:
np.random.rand(3, 2, 4) #membuat 3 dimensi

array([[[0.20489196, 0.29265123, 0.84915623, 0.10150062],
        [0.26549051, 0.19077859, 0.20313639, 0.41785087]],

       [[0.56867642, 0.91482267, 0.50977039, 0.78072147],
        [0.49991953, 0.37909065, 0.4047006 , 0.70268023]],

       [[0.05262714, 0.62409168, 0.63133923, 0.68945165],
        [0.20500658, 0.14305009, 0.67015912, 0.40415523]]])

Random terdistribusi normal

In [ ]:
np.random.randn() #membuat angka randome yang terdistribusi normal

0.44066977942748764

In [ ]:
np.random.randn(3) #array 1 dimensi normal

array([ 2.0624249 , -0.35070356,  0.20157744])

Random integer yang berisi rentangnya

In [ ]:
np.random.randint(1, 100, 20)
# 1 : Angka awal, 100 : angka akhir, 20 : rentang

array([30, 41, 59, 61, 31, 21, 49, 80, 27, 43, 48, 92, 73, 51, 55, 52, 98,
       89, 48,  6])

Tatangan : membuat fungsi random int membuat angka 1 - 100 dengan ukuran array 3x3

In [ ]:
np.random.randint(1, 101, size = (3, 3))

array([[ 22, 100,  99],
       [ 99,  62,  83],
       [  3,  24,  92]])

# Membuat Angka Random Sesuai Distribusi

In [ ]:
import numpy as np

Distribusi Uniform

In [ ]:
np.random.uniform?


In [ ]:
np.random.uniform(0, 10, 10)

array([5.75166431, 9.85456859, 0.30983875, 4.08965704, 8.4744862 ,
       1.30826386, 1.61276641, 0.46904435, 9.89849058, 6.50021699])

In [ ]:
# menggunakan ukuran array 2x2
np.random.uniform(0, 10, (2, 2))

array([[4.51858786, 9.25655287],
       [9.70765774, 2.38457122]])

Distribusi normal

In [ ]:
np.random.normal?

In [ ]:
np.random.rand(10) # hnya dng rentang 0 - 1

array([0.30774906, 0.11211621, 0.94548616, 0.80178875, 0.43789651,
       0.8328558 , 0.1791473 , 0.0088339 , 0.96684378, 0.41884769])

In [ ]:
np.random.normal(loc=10, scale=10, size=(4,4))#modifikasi sesuai yg diinginkan
# loc = rata rata, scale = variasi

array([[26.08378845,  2.84945764,  0.51389158, 13.83833905],
       [23.59306309, -5.66324508, -4.8358318 ,  8.75288436],
       [-4.92619419,  6.12987626,  8.49357054,  7.00258446],
       [13.07975973, 18.04771372, 23.19709185,  3.35088555]])

Distribusi Binomial

In [ ]:
np.random.binomial?

In [ ]:
np.random.binomial(100, 0.5, 5)
# 100 rentang, 0.5 probabilitas, 5 elemen

array([53, 52, 44, 48, 49])

Distribusi Poissont

In [ ]:
np.random.poisson?

In [ ]:
np.random.poisson(4, 10)
# 4 rentang, 10 jmlh elemen

array([ 9,  5,  5,  4, 11,  3,  2,  4,  4,  5])

# Random Seed

In [58]:
import numpy as np

In [65]:
np.random.randint(1,10, (3,3))

array([[9, 4, 9],
       [8, 4, 7],
       [6, 2, 4]])

In [79]:
#menggunakan random seed
np.random.seed(1) #untuk mengunci seed
np.random.randint(1,10, (3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [80]:
#menggunakan random seed
np.random.seed(2)
np.random.randint(1,10, (3,3))

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6]])

Tantangan :

In [82]:
np.random.seed(7)
np.random.randint(1, 100, (4,4))

array([[48, 69, 26, 68],
       [84, 24, 93, 58],
       [15, 24, 73, 90],
       [43, 91,  9, 40]])

# Latihan Module Random NumPy

1.Buatkan array dengan bilangan random integer ukuran 3x3 (nilai elemen tidak harus sesuai dengan solusi)

In [83]:
np.random.randint(1,100, (3,3))

array([[69, 49,  8],
       [45,  1, 76],
       [56,  7, 20]])

2. Buatkan array dengan bilangan random terdistribusi normal, dengan mean=4 dan variance=10, dan ukuran 3x3 (nilai elemen tidak harus sesuai dengan solusi)

In [84]:
np.random.normal(loc=4, scale=10, size=(3, 3))

array([[ -6.42042225,  17.12685509,   2.67975661],
       [  6.38855514,  -4.32720173,  12.5193849 ],
       [  1.1971449 ,   7.02081967, -17.4511962 ]])

3. Dengan seed = 101, buatkan angka random sesuai dengan solusi di soal no. 2

In [88]:
np.random.seed(101)
np.random.normal(loc=4, scale=10, size=(3, 3))

array([[ 31.06849839,  10.28132709,  13.07969446],
       [  9.03825754,  10.51117948,   0.80681955],
       [ -4.48076983,  10.05965349, -16.18168244]])