<a href="https://colab.research.google.com/github/aqilaazza/mini-bootcamp-data-analyst-python/blob/main/01-basic-python/numpy-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Membuat array Dari List

Array Multidimensi : lebih dari 1 dimensi
Array umumnya digunakan hanya pada satu tipe data

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [4]:
np.array?

In [5]:
a = [1,2,3,4]
b = [[1, 2], [3, 4]]

In [6]:
#array 1  dimensi
np.array(a)

array([1, 2, 3, 4])

In [7]:
#jumlah elemen
np.array(a).shape

(4,)

In [8]:
#array 2 dimensi
np.array(b)

array([[1, 2],
       [3, 4]])

In [9]:
c = [b,b]
c

[[[1, 2], [3, 4]], [[1, 2], [3, 4]]]

In [10]:
# array 3d dimensi
np.array(c)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

# Membuat Array dari Fungsi

In [11]:
np.zeros(5) # membuat array dengan elemen bernilai 0

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3)) #array 2 baris 3 kolom

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [17]:
np.arange(10) #urutan dari parameter

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange (1,11) #1 adalah start

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1,10,2) #ganjil

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(1,2,5)
#parameter 1 = start
#parameter 2 = stop
#parameter 3 = jumlah elemen

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Tantangan : Array Bilangan Genap 1 - 10

In [22]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Indexing dan Slicing pada Array

Mengambil nilai/potongan nilai dari array

In [23]:
# Array 1 dimensi
arr_a = np.array(a)
arr_a

array([1, 2, 3, 4])

In [24]:
arr_a[0]

np.int64(1)

In [25]:
arr_a[0:2]

array([1, 2])

In [26]:
# Array 2 dimensi
arr_b = np.array(b)
arr_b

array([[1, 2],
       [3, 4]])

In [27]:
arr_b[1,0]

np.int64(3)

In [28]:
arr_b[:,0]

array([1, 3])

In [29]:
# Array 3 dimensi
arr_c = np.array(c)
arr_c

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

Tantangan : mendapatkan nilai 2

In [30]:
arr_c[1, 0, 1]
#baris, baris in, kolom

np.int64(2)

# Reassignment dan Operasi Matematika pada Array

Mengubah nilai pada array

In [31]:
arr_contoh = np.array([[1,2,3],[4,5,6,],[7,8,9,]])
arr_contoh

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#mengubah nilai 1 menjadi 100
arr_contoh[0,0] = 100

In [33]:
arr_contoh

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [34]:
#Mengubah baris 1 menjadi 100
arr_contoh[0] = 100

In [35]:
arr_contoh

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [36]:
arr_contoh = np.array([[1,2,3],[4,5,6,],[7,8,9,]])
arr_contoh

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#Mengalikan semua menjadi 2
arr_contoh * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [38]:
#Membagi semua menjadi 2
arr_contoh/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [39]:
#Menambah semua 10
arr_contoh+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [40]:
#Menambah sesama
arr_contoh + arr_contoh

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
arr_contoh2 = np.array([[10,20,30],[40,50,60,],[70,80,90,]])
arr_contoh2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
#Menambah arr_contoh dan arr_contoh2
arr_contoh + arr_contoh2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

Tantangan pada baris 0 ditambah 1, baris 1 ditambah 2 dan baris 2 ditambah 3

In [44]:
arr_contoh

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr_contoh3 = np.array([1,2,3])

In [46]:
arr_contoh + arr_contoh3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

#Manipulasi Bentuk/Dimensi Array

In [47]:
arr_contoh.shape

(3, 3)

In [48]:
arr_contoh.flatten() #mengubah apapun menjadi array 1 dimensi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr_contoh.reshape(9,1) #mengubah array menjadi (9 x 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
arr_contoh.reshape(2,3) #akan error karna jumlahnya adalah 9

ValueError: cannot reshape array of size 9 into shape (2,3)

In [51]:
arr_contoh #array 2 dimensi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Tantangan membuat array 3 dimensi

In [53]:
arr_contoh.reshape(3,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

# Attribute dan Fungsi Statistik pada Array

In [54]:
arr_a

array([1, 2, 3, 4])

In [55]:
arr_b

array([[1, 2],
       [3, 4]])

In [56]:
arr_c

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [58]:
arr_c.shape

(2, 2, 2)

In [59]:
arr_a.ndim #mengembalikan nilai 1 yang berarti 1 dimensi

1

In [60]:
arr_b.ndim

2

In [61]:
arr_c.ndim

3

In [62]:
arr_a.size #mengembalikan jumlah elemen di dalam array

4

In [63]:
arr_b.size

4

In [64]:
arr_c.size

8

In [65]:
arr_c.dtype #mengembalikan tipe data dalam array

dtype('int64')

In [66]:
arr_d = np.array(['a', 'b', 'c'])

In [67]:
arr_d.dtype

dtype('<U1')

In [68]:
arr_b.mean() #rata rata

np.float64(2.5)

In [70]:
arr_b.max() #tertinggi

np.int64(4)

In [71]:
arr_b.sum() #jumlah semua elemen

np.int64(10)

Tantangan : mengembalikan nilai berdasarkan baris

In [72]:
arr_b

array([[1, 2],
       [3, 4]])

In [75]:
arr_b.sum(axis=0)

array([4, 6])

In [76]:
arr_b.sum(axis=1)

array([3, 7])

# Latihan NumPy Array